quickreload.service.start_scan_dir=Start scan target dir {0}
quickreload.service.failed_scan_dir=Failed to scan directory {0}
quickreload.service.fonded_file=Fonded file {0}
quickreload.service.failed_read_file=Failed to read file {0}
