#!/usr/bin/env bash

LUNA_SDK_MAVEN_VER=${apache.maven.version}

if [[ -z "${LUNA_SDK_DIR}" ]] ; then
  SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
  LUNA_SDK_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)
fi

JAVA="${JAVA:-java}"

JAR_LIB_DIR="$LUNA_SDK_DIR/libs"

"$JAVA" -cp "$JAR_LIB_DIR/*" -Dfile.encoding=UTF-8 -Dmvn.directory="$LUNA_SDK_DIR/apache-maven-$LUNA_SDK_MAVEN_VER" -Dluna.sdk.home="$LUNA_SDK_DIR" -Dmnv.repository="$LUNA_SDK_DIR/repository" "ru.slie.luna.sdk.LunaCliMain" "$@"