#!/usr/bin/env bash

if [[ -n "${_OLD_LUNA_SDK_PATH}" ]] ; then
    deactivate
fi

LUNA_SDK_VERSION=${version}
LUNA_SDK_MAVEN_VER=${apache.maven.version}
_OLD_LUNA_SDK_PATH=${PATH}
_OLD_LUNA_SDK_PS1=${PS1}

SCRIPT_DIR=$(cd -- "$(dirname -- "$0")" && pwd)
LUNA_SDK_DIR=$(cd -- "$SCRIPT_DIR/.." && pwd)

deactivate() {
    if [[ -n "${_OLD_LUNA_SDK_PATH}" ]] ; then
        PATH="${_OLD_LUNA_SDK_PATH}"
        export PATH
        unset _OLD_LUNA_SDK_PATH
    fi

    if [[ -n "${_OLD_LUNA_SDK_PS1}" ]] ; then
        PS1="${_OLD_LUNA_SDK_PS1}"
        export PS1
        unset _OLD_LUNA_SDK_PS1
    fi
    unset LUNA_SDK_MAVEN_VER
    unset LUNA_SDK_DIR

    hash -r 2>/dev/null
}

PATH=${LUNA_SDK_DIR}/bin:${LUNA_SDK_DIR}/apache-maven-${LUNA_SDK_MAVEN_VER}/bin:$PATH
export LUNA_SDK_DIR
export PATH
hash -r 2>/dev/null

PS1="(luna-sdk ${LUNA_SDK_VERSION}) ${PS1-}"
